### ISSUE TITLE
SSL Handshake Failed

### ISSUE THREAD

**Issue by KingLinkTiger** [wireload/screenly-ose#234]
I'm receiving an error that sates "SSL Handshake Failed." When this error appears the display freezes with the error window (See image below) and does not advance thought he playlist. My current fix for this is to restart the system. I believe this to be caused by the loading of secure HTTPS content onto the display. In this instance I'm loading Google Slides presentations. Is there any way I can prevent this or fix this from happening again?

![image](https://cloud.githubusercontent.com/assets/1048576/4720306/22b77834-5930-11e4-88b9-96ec9ae4de60.png)

**Comment by SebastianSchildt** [comment]
Ah this is an old issue, but maybe this is helpful for somebody: 

 We had the same problem last year. This problem could not be 100% solved. The main problem is, uzbl displays this, when it is unhappy with the SSL handshake, and refuses to accept further commands unitl somebody clicks on the requester. 

So for many causes (bad certs etc.) ``verify_ssl = False`` indeed solves the problem.

However, we noticed it also happens, when the network connection breaks down exactly during the SSL handshake. We had the problem last year with a Pi and Screenly that was connected via Wi-Fi: The Pi's poor processor combined with its braindead USB controller and a modern (read: cheap, all the work done in software) Wi-Fi dongle while running uzbl was too much for the Pi, and the Wi-Fi connection dropped very often, leading to the error described here.

This being said, when using ethernet you should be pretty save (for that particular installation we just attached an old Ubiquiti PicoStation to the PI, which is doing the Wi-Fi-to-Ethernet conversion, and it has been fine ever since)

**Comment by vpetersson** [comment]
@SebastianSchildt Yes, this, along with a long range of other reasons, is why we don't support WiFi in Screenly Pro. :)

**Comment by vpetersson** [comment]
@KingLinkTiger Since we haven't heard back from you, I'm going to close down the issue.
