### ISSUE TITLE
'module' object has no attribute 'codegen'

### ISSUE THREAD

**Issue by vpetersson** [wireload/screenly-ose#477]
I tried the latest master branch today and it's not starting. 

Here's what the logs are saying:

![img_1328](https://cloud.githubusercontent.com/assets/357664/18028766/93706dca-6c7e-11e6-9373-db5feeab1f0b.jpg)

**Comment by over64** [comment]
It's strange, but master branch contains requirements.txt with pyhaml of 1.1.0 version. But in local repo I have pyhaml with 0.1.9 version. I changed version to 1.1.0 when first PR for email-signup was made. After this I reverted version back to 0.1.9 because update was not needed. BUT something happened bettwen pull requests reopen and merges. Need to revert pyhaml version to 0.1.9 in master

**Comment by vpetersson** [comment]
Fixed in #484.
